INSERT INTO jobs (employer_id, title, description, requirements, location, job_type, salary_range, status)
VALUES
(1, 'Software Engineer', 'Develop web applications.', 'PHP, JavaScript, MySQL', 'Kuala Lumpur', 'full-time', 'RM4000 - RM6000', 'Open'),
(1, 'Marketing Intern', 'Assist with campaigns.', 'Communication, Social Media', 'Petaling Jaya', 'internship', 'RM1000 - RM1500', 'Open'),
(1, 'Data Analyst', 'Analyze data trends.', 'Excel, SQL, Python', 'Remote', 'full-time', 'RM3500 - RM5000', 'Open'),
(1, 'Graphic Designer', 'Design marketing materials.', 'Photoshop, Illustrator', 'Kuala Lumpur', 'part-time', 'RM2000 - RM3000', 'Open'),
(1, 'HR Assistant', 'Support HR operations.', 'Organization, MS Office', 'Subang Jaya', 'contract', 'RM2500 - RM3500', 'Open'),
(1, 'Customer Service Rep', 'Handle customer inquiries.', 'Communication, Patience', 'Penang', 'full-time', 'RM2500 - RM3500', 'Open'),
(1, 'Business Analyst', 'Analyze business processes.', 'Excel, PowerPoint, SQL', 'Cyberjaya', 'full-time', 'RM4000 - RM6000', 'Open'),
(1, 'Content Writer', 'Write blog posts and articles.', 'Writing, SEO', 'Remote', 'part-time', 'RM1500 - RM2500', 'Open'),
(1, 'Sales Executive', 'Drive sales growth.', 'Negotiation, CRM', 'Kuala Lumpur', 'full-time', 'RM3500 - RM5000', 'Open'),
(1, 'IT Support', 'Provide technical support.', 'Windows, Networking', 'Shah Alam', 'full-time', 'RM3000 - RM4000', 'Open'),
(1, 'Finance Intern', 'Assist with financial reports.', 'Excel, Accounting', 'Petaling Jaya', 'internship', 'RM1000 - RM1500', 'Open'),
(1, 'Operations Manager', 'Oversee daily operations.', 'Leadership, Organization', 'Kuala Lumpur', 'full-time', 'RM6000 - RM8000', 'Open'),
(1, 'UX Designer', 'Design user interfaces.', 'Figma, UX Research', 'Remote', 'full-time', 'RM4000 - RM6000', 'Open'),
(1, 'Project Coordinator', 'Coordinate project tasks.', 'Planning, Communication', 'Subang Jaya', 'contract', 'RM3500 - RM4500', 'Open'),
(1, 'Mobile App Developer', 'Develop mobile apps.', 'Flutter, Android, iOS', 'Kuala Lumpur', 'full-time', 'RM5000 - RM7000', 'Open'),
(1, 'Legal Assistant', 'Support legal team.', 'Legal Research, MS Office', 'Cyberjaya', 'part-time', 'RM2000 - RM3000', 'Open'),
(1, 'Digital Marketing Specialist', 'Manage digital campaigns.', 'Google Ads, Facebook Ads', 'Remote', 'full-time', 'RM4000 - RM6000', 'Open'),
(1, 'QA Tester', 'Test software applications.', 'Testing, Selenium', 'Kuala Lumpur', 'full-time', 'RM3500 - RM5000', 'Open'),
(1, 'Administrative Assistant', 'General admin support.', 'Organization, MS Office', 'Penang', 'full-time', 'RM2500 - RM3500', 'Open'),
(1, 'Research Assistant', 'Assist with research projects.', 'Research, Data Analysis', 'Sunway', 'internship', 'RM1200 - RM1500', 'Open'); 